# Use an official Python runtime as a parent image
FROM python:3.11.3-slim

WORKDIR /app

# Copy the project files
COPY . /app

RUN ls

# Install packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

ENTRYPOINT ["python", "src/main.py"]
