FROM python:3.9-slim

WORKDIR /app

ENV PYTHONUNBUFFERED=1

# Add debugging tools (ping, netcat)
RUN apt-get update && apt-get install -y iputils-ping netcat-openbsd


# Copy requirements first (better caching)
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copy all source code (including .env)
COPY . /app

# Expose Flask port
EXPOSE 9000

CMD ["python", "logging_service.py"]
