name: Build and Push refundService Docker Image to AWS ECR

on:
  push:
    branches:
      - main
    paths:
      - 'services/refundService/**'

  workflow_dispatch: # This enables the manual run button 

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}

jobs:
  build-and-push:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Tag Docker Image
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:refundService-latest ./services/refundService
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:refundService-latest $ECR_REGISTRY/$ECR_REPOSITORY:refundService-${{ github.sha }}

      - name: Push Images to AWS ECR
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:refundService-latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:refundService-${{ github.sha }}

